[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read", path = "lib/foundry-chainlink-toolkit/out"}]

remappings = [
  '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
]

# Configuración de lints - UNA SOLA SECCIÓN
[profile.lints]
unsafe-typecast = "ignore"
